### ISSUE TITLE
Condition file not found

### ISSUE THREAD

**Issue by zaizibai** [neuropsychology/ComplexSpan#6]
Dear Zen,

Thank you for this wonderful work. When I try the task, after finishing the first one, there is some warning at the beginning of the second task. It seems there is no codnition file input?

Traceback (most recent call last):
  File "D:\Onedrive\experiment\py-span-task-master\EnglishOperationSpan\task_lastrun.py", line 864, in <module>
    trialList=data.importConditions('..\\materials\\processing_only_2.xlsx'),
  File "C:\Program Files (x86)\PsychoPy3\lib\site-packages\psychopy\data\utils.py", line 231, in importConditions
    raise ValueError(msg % os.path.abspath(fileName))
ValueError: Conditions file not found: D:\Onedrive\experiment\py-span-task-master\materials\processing_only_2.xlsx

**Comment by zen-juen** [comment]
Hi @zaizibai, thanks for raising this! That's odd, did you clone this entire repository with the [materials](https://github.com/neuropsychology/ComplexSpan/tree/master/materials) subfolder?
